### PR TITLE
closes #2 Starting services with docker-compose

### LINKED ISSUE #2: Starting services with docker-compose
We should be able to start all services using Docker following this [example](http://www.kennybastani.com/2015/07/spring-cloud-docker-microservices.html). Before _dockerization_ services can be started locally as described in README.

### PR DESCRIPTION
**Pull request by mszarlinski**
Finally I managed to setup a Docker configuration, so that the entire application can be started with docker-compose. I will publish images to docker hub in a couple days, so they will be available without a need of building them locally before application startup.
Please review @arey @ryanjbaxter

### CODE REVIEW

**Comment by arey** [comment]
I will test it.

**Comment by mszarlinski** [comment]
Ok, thanks. I expect some problems with order of containers startup. If you encounter any problem, please follow the following steps:

1. Start config server with `docker-compose up -d config-server`.
2. Start Eureka with `docker-compose up -d discovery-server`.
3. Start remaining services with `docker-compose up`.

Maybe I should add it to README.

**Comment by arey** [comment]
@mszarlinski I've checkout your docker-compose branch then I've executed the ```mvn clean install -PbuildDocker`` command line and I've got the following error:
```
INFO] Building image mszarlinski/spring-petclinic-customers-service
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] spring-petclinic-microservices ..................... SUCCESS [  0.208 s]
[INFO] spring-petclinic-ui ................................ SUCCESS [ 12.660 s]
[INFO] spring-petclinic-monitoring ........................ SUCCESS [  0.765 s]
[INFO] spring-petclinic-customers-service ................. FAILURE [ 29.624 s]
[INFO] spring-petclinic-vets-service ...................... SKIPPED
[INFO] spring-petclinic-visits-service .................... SKIPPED
[INFO] spring-petclinic-config-server ..................... SKIPPED
[INFO] spring-petclinic-discovery-server .................. SKIPPED
[INFO] spring-petclinic-api-gateway ....................... SKIPPED
[INFO] spring-petclinic-tracing-server .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.825 s
[INFO] Finished at: 2016-12-15T19:23:39+01:00
[INFO] Final Memory: 86M/944M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project spring-petclinic-customers-service: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-petclinic-customers-service
```

After having updating the docker-maven-plugin to the latest version 0.4.13 the build is passing.

**Comment by arey** [comment]
Just a few remarks: maven version is hardcoded into the Dockerfile:
```
ADD spring-petclinic-discovery-server-1.4.2.jar /app.jar
```
Maybe could we use joker?

**Comment by arey** [comment]
I've got a lot of error even if I manually check config-server and discovery-server startup.
Maybe could we enhance startup order by waiting HTTP port is open?
See https://docs.docker.com/compose/startup-order/ and the ```wait-for-it.sh``` script.

**Comment by mszarlinski** [comment]
Thanks for advice, I will try to fix it with https://github.com/vishnubob/wait-for-it

**Comment by arey** [comment]
@mszarlinski  The docker.plugin.version 0.3.258 is very old and do not work on macosx. Please upgrade to the last one.

**Comment by mszarlinski** [comment]
@arey containers startup has been fixed with [wait-for-it.sh](https://github.com/vishnubob/wait-for-it)

**Comment by arey** [comment]
I've got timeout at startup even though I may ping my config server http://localhost:8888/info
```
config-server        | 2016-12-30 20:02:55.761  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshEndpoint': registering with JMX server as MBean [org.springframework.cloud.endpoint:name=refreshEndpoint,type=RefreshEndpoint]
config-server        | 2016-12-30 20:02:55.856  INFO 1 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
config-server        | 2016-12-30 20:02:55.974  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8888 (http)
config-server        | 2016-12-30 20:02:55.978  INFO 1 --- [           main] o.s.s.p.config.ConfigServerApplication   : Started ConfigServerApplication in 5.63 seconds (JVM running for 6.785)
config-server        | 2016-12-30 20:02:59.815  INFO 1 --- [nio-8888-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
config-server        | 2016-12-30 20:02:59.815  INFO 1 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
config-server        | 2016-12-30 20:02:59.832  INFO 1 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 16 ms
discovery-server     | wait-for-it.sh: timeout occurred after waiting 15 seconds for config-server:8888/info
tracing-server       | wait-for-it.sh: timeout occurred after waiting 15 seconds for discovery-server:8761/manage/health
tracing-server       | Error: Invalid or corrupt jarfile /app.jar
visits-service       | wait-for-it.sh: timeout occurred after waiting 15 seconds for discovery-server:8761/manage/health
vets-service         | wait-for-it.sh: timeout occurred after waiting 15 seconds for discovery-server:8761/manage/health
```

**Comment by mszarlinski** [comment]
I've pushed a fix and containers are starting properly. Could you please investigate missing traces in `tracing-server`? Nothing is logged.

**Comment by arey** [comment]
Default timeout (15 seconds) is still there. I think we may increase it to 1mn. Don't you?
```
config-server        | 2016-12-31 16:52:52.926  INFO 1 --- [nio-8888-exec-2] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 14 ms
customers-service    | wait-for-it.sh: timeout occurred after waiting 15 seconds for discovery-server:8761
tracing-server       | wait-for-it.sh: timeout occurred after waiting 15 seconds for discovery-server:8761
config-server        | 2016-12-31 16:53:00.365  INFO 1 --- [nio-8888-exec-2] s.c.a.AnnotationConfigApplicationCont
```

**Comment by mszarlinski** [comment]
You are right. I thought waiting is done in a loop, but it is not true for timeout>0.

**Comment by arey** [comment]
I've started 3 times ```docker-compose up``` and I always had the following error with visits-service or pets-service:
```
visits-service exited with code 137
```

**Comment by arey** [comment]
On tracing-server startup, I've got the following error:
```
tracing-server       | 2016-12-31 18:22:29.813  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
tracing-server       | 2016-12-31 18:22:50.449 ERROR 1 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error
```

**Comment by mszarlinski** [comment]
Unfortunately, I am unable to reproduce any of reported issues. 

Code 137 stands for `SIGKILL`, so JVM process was killed from outside somehow. Please also make sure that Eureka server is running while Zipkin server is starting up - maybe it has been terminated too?

**Comment by arey** [comment]
In order micro-services could reach the tracing-server, I think you have to add a link to the tracing-server (and maybe a depends on?):
```
  visits-service:
    image: mszarlinski/spring-petclinic-visits-service
    container_name: visits-service
    links:
     - config-server
     - discovery-server
     - tracing-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./wait-for-it.sh","discovery-server:8761","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8082:8082
```
In this way, Docker compose will open a network route between the tracing server and each microservice.

**Comment by mszarlinski** [comment]
I will check 'depends_on' as it injects an address of tracing-server to given container

**Comment by mszarlinski** [comment]
Zipkin tracing doesn't work even when starting services without Docker, so this is a bug not related to the Docker configuration. Should I open separate issue for that?

**Comment by arey** [comment]
Of course, if tracing server does not work without Docker, we could open a new issue.
For this PR, my last comments is about the hard-coded version of the maven version in Dockerfile:
```
ADD spring-petclinic-discovery-server-1.4.2.jar /app.jar
```
I don't know if we could use joker or not in Dockerfile. If not, we could customize the  Maven ```<finalName>```

**Comment by mszarlinski** [comment]
Nice, will look into that as well!

**Comment by arey** [comment]
By debugging what happen with the tracing server, I've saw that model update/save logs have been removed by the commit: https://github.com/spring-petclinic/spring-petclinic-microservices/commit/769c22935a343f06836846e5677c1b58d685296f
We should reintroduce them. Example in OwnerResource:
```
        LOG.info("Saving owner {}", ownerModel);
        return ownerRepository.save(ownerModel);
```

**Comment by arey** [comment]
I've found why zipkin did not receive any traces.
We have to add the following dependency into the spring-petclinic-api-gateway pom.xml:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin</artifactId>
        </dependency>
```

**Comment by mszarlinski** [comment]
I've added `ARTIFACT_NAME` parameter to Dockerfiles. Let's fix Zipkin issue in new issue: #31

**Pull request merged**
