### PR TITLE
Upgrade to Spring Cloud 2023.0.0

### PR DESCRIPTION
**Pull request by shobhakamath**
Upgrade to Spring Cloud 2023.0.0 also requires springboot upgrade 3.2.0.
 LTS Java 17 compatible to Springboot 3.2.0

### CODE REVIEW

**Comment by arey** [comment]
Hi @shobhakamath 
Before merging your PR, could you please test the Docker images built against this Spring Cloud version?

**Comment by arey** [comment]
Be careful because I recently removed `dockerize`: https://github.com/spring-petclinic/spring-petclinic-microservices/pull/247

**Comment by shobhakamath** [comment]
Thank you for your comment. I have fixed the entry point and the container is up and running perfectly.

Screenshot 2023-12-28 at 2 35 36 PM

**Comment by arey** [comment]
Great job @shobhakamath 
Thanks :)

**Pull request merged**
